In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#   number of demensions
scalar.ndim

0

In [4]:
# vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# matrix
matrix =tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
matrix01 =tf.constant([[104.,47.,8.],[17.,130.,3.],[8.,0.,1.]], dtype=tf.float16)
matrix01

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[104.,  47.,   8.],
       [ 17., 130.,   3.],
       [  8.,   0.,   1.]], dtype=float16)>

In [9]:
matrix01.ndim

2

In [10]:
# tensor
tensor=tf.constant([[[1,2,3],[4,8,9]],[[4,5,3],[4,9,9]],[[1,2,3],[4,8,9]],[[4,5,3],[4,9,9]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 8, 9]],

       [[4, 5, 3],
        [4, 9, 9]],

       [[1, 2, 3],
        [4, 8, 9]],

       [[4, 5, 3],
        [4, 9, 9]]])>

In [11]:
tensor.ndim

3

In [12]:
chengable_tensor = tf.Variable([10,7])
unchengable_tensor = tf.constant([10,7])
chengable_tensor, unchengable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
chengable_tensor[0]
chengable_tensor[0].assign(7)
chengable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [14]:
unchengable_tensor[0] 


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
# Random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# shuffle the order of elements in a tensors

not_shuffled = tf.constant([[10,7],[5,12],[4,9],[1,4]])
not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 5, 12],
        [ 4,  9],
        [ 1,  4]])>,
 2)

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 5, 12],
       [ 4,  9],
       [10,  7],
       [ 1,  4]])>

In [19]:
# other ways to make tensors

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# All zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [22]:
# numpy arrays into tensors
import numpy as np

numpy_A= np.arange(1,25, dtype = np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
A = tf.constant(numpy_A, shape =(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [26]:
A.ndim

3

In [27]:
# getting information from tensors

# shape, rank, axis or dim, size

rank_4_tensors = tf.zeros(shape=[2,3,4,5])
rank_4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensors[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
rank_4_tensors.shape, rank_4_tensors.ndim, tf.size(rank_4_tensors)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [36]:
print("Datatype: ", rank_4_tensors.dtype)
print("Number of dimensions: ", rank_4_tensors.ndim)
print("Shape of tensor: ", rank_4_tensors.shape)
print("Elements along the 0 axis: ", rank_4_tensors.shape[0])
print("Elements along the last axis: ", rank_4_tensors.shape[-1])
print("Total number of elements: ", tf.size(rank_4_tensors).numpy())

Datatype:  <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  120


In [40]:
# Indexing tensors(like python list)

rank_4_tensors[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [46]:
rank_4_tensors[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [52]:
# create a rank 2 tensors (2)

rank_2_tensors = tf.constant([[4,11],[8,0]])
rank_2_tensors.shape, rank_2_tensors.ndim

(TensorShape([2, 2]), 2)

In [55]:
# last item of each of our rank 2 tensor

rank_2_tensors[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11,  0])>

In [57]:
# add in extra dimension
rank_3_tensors =rank_2_tensors[..., tf.newaxis]
rank_3_tensors

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 4],
        [11]],

       [[ 8],
        [ 0]]])>

In [58]:
# Alternative

tf.expand_dims(rank_2_tensors, axis =-1) # "-1" final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 4],
        [11]],

       [[ 8],
        [ 0]]])>

In [61]:
tf.expand_dims(rank_2_tensors, axis =0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 4, 11],
        [ 8,  0]]])>

In [63]:
# Manipulating tensors (tensor operations)

# add value to a tensor using additional operator

tensor = tf.constant([[10,7],[3,4]])
tensor+10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [64]:
tensor * 10, tensor -10


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>)

In [65]:
#  built-in function

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>